DATASET:
  # DATASET_PATH: datasets_for_train_eiei
  DATASET_PATH: /home/kansmarts777/wsl_code/ABC_full_project/dataset_process_final/digital/digital_f_color
  DATASET_TYPE: digital
MODEL:
  MODEL: 
    MODEL_NAME: YOLO
    MODEL_VERSION: 8 
    MODEL_TYPE: m
  MODEL_PATH: null
TRAIN_PARAMETERS:
  BATCH_SIZE: 4
  CACHE: false
  DEVICE: 0
  EPOCHS: 20
  FINAL_LEARNING_RATE: 0.001
  IMG_SIZE: 640
  LEARNING_RATE: 0.001
  PATIENCE: 15
  RESUME: false
  WORKERS: 1