DATASET:
  # DATASET_PATH: datasets_for_train_eiei
  DATASET_PATH: dataset_new
  DATASET_TYPE: digital
MODEL:
  MODEL: 
    MODEL_NAME: YOLO
    MODEL_VERSION: 9 
    MODEL_TYPE: c
  MODEL_PATH: null
TRAIN_PARAMETERS:
  BATCH_SIZE: 4
  CACHE: false
  DEVICE: 0
  EPOCHS: 20
  FINAL_LEARNING_RATE: 0.01
  IMG_SIZE: 640
  LEARNING_RATE: 0.001
  PATIENCE: 15
  RESUME: false
  WORKERS: 4