DATASET:
  DATASET_PATH:
  #TODO: for number dataset
  - dataset_process_final/clock/clock_min_max_gray_final/clock
  DATASET_TYPE: clock
  FINAL_DATASET_PATH: dataset_process_final/clock/clock_min_max_gray_ero_final/clock 
  PERCENT_TEST: 1
  PERCENT_TRAIN: 98
  PERCENT_VAL: 1
PREPROCESS:
  FOLDER:
  - train
  - valid
  - test
  PREFIX: pre
  PREPROCESS_LIST: 
  - GRAY_EROSION_DILATE:
      P: 1.0
      REPLACE: true
AUGMENT:
  AUGMENT_LIST: []  
  FOLDER:
  - train
  NUMBER_AUGMENT: 3 # augment 3 image for own dataset
  PREFIX: aug