AUGMENT:
  AUGMENT_LIST: []  
   # - RESIZE:
   #     TARGET_WIDTH: 640
   #     TARGET_HEIGHT: 640
   #     REPLACE: true
   # - CHANNEL_SHUFFLE:
   #    P: 0.25
   #    REPLACE: false
   # - MULTIPLICATIVE_NOISE:
   #    MULTIPLIER:
   #    - 0.4
   #    - 1.0
   #    ELEMENT_WISE: true
   #    P: 0.25
   #    REPLACE: false
   # - BLUR:
   #    BLUR_LIMIT:
   #    - 3
   #    - 3 
   #    P: 0.25
   #    REPLACE: false
   # - ROTATE:
   #    LIMIT:
   #    - -20
   #    - 20 
   #    P: 0.25
   # - COLOR_JITTER:
   #    BRIGHTNESS: 0.5
   #    CONTRAST: 0.5
   #    SATURATION: 0.5
   #    HUE: 0.5
   #    P: 0.5
   #    REPLACE: false
   # - LONGEST_MAX_SIZE:
   #    MAX_SIZE: 640
   #    P: 1.0
   #    REPLACE: false
   # - PAD_IF_NEEDED:
   #    MIN_WIDTH: 640
   #    MIN_HEIGHT: 640
   #    P: 1.0
   #    REPLACE: false
  #  - GRAY:
  #     P: 1.0
  #     REPLACE: false
  FOLDER:
  - train
  # - valid
#   - test
  NUMBER_AUGMENT: 3
  PREFIX: aug
DATASET:
  DATASET_PATH:
  # for number dataset
  # - test_clock_dataset
  - test_set1_693
  # - /Users/kantip/Desktop/work/ABC_full_project/dataset/clock/set1_300
#   - /home/kan.t/work/ABC_full_project/datasets/number/user13/permanent_set1_3600
#   - /home/kan.t/work/ABC_full_project/datasets/number/user14/permanent_set1_2800
#   - /home/kan.t/work/ABC_full_project/datasets/number/svhn/finish_dataset/test
#   - /home/kan.t/work/ABC_full_project/datasets/number/svhn/finish_dataset/train
#   - /home/kan.t/work/ABC_full_project/datasets/number/svhn/finish_dataset/extra
  
  DATASET_TYPE: clock
  FINAL_DATASET_PATH: dataset_process/clock/test_clock_dataset/clock
  PERCENT_TEST: 0
  PERCENT_TRAIN: 100 
  PERCENT_VAL: 0
PREPROCESS:
  FOLDER:
  - train
  - valid
  - test
  PREFIX: pre
  PREPROCESS_LIST:
  - CROP:
      ADD_PIXEL: 0
      CLASS_CROP_LIST: 
      - 0
      CLASS_IGNORE: []
      NEED_RESIZE: true
      TARGET_HEIGHT: 640
      TARGET_WIDTH: 640
      REPLACE: true
      REMOVE_ORIGINAL: true
  - RESIZE:
      TARGET_HEIGHT: 640
      TARGET_WIDTH: 640
      REPLACE: true
  - CLOCK:
      PREPROCESS_MIN_HEAD: false # remove min that overlap with head
      PREPROCESS_MIN_MAX: true # when have multiple min and max use the average min, max
      PREPROCESS_ONLY_ONE_GAUGE: true # choose image that has only one gauge in each image
      PREPROCESS_FULL_CLASS: true # choose image that has min, max , head, center
      REPLACE: true
  - RESIZE_BB:
      PERCENT: 100
      CLASS : [1,2] # add size of min and max
      REPLACE: true
  - RESIZE_BB:
      PERCENT: 150
      CLASS : [4] # add size of head
      REPLACE: true
  
  
  #     REPLACE: true
#   - GRAY:
#       P: 1.0
#       REPLACE: true
  # - GRAY_EROSION_DILATE:
  #     P: 1.0
  #     REPLACE: true