AUGMENT:
  AUGMENT_LIST: 
  #  - RESIZE:
  #      TARGET_WIDTH: 320
  #      TARGET_HEIGHT: 320
  #      REPLACE: true
  # - CHANNEL_SHUFFLE:
  #     P: 1.0
  #     REPLACE: false
  # - MULTIPLICATIVE_NOISE:
  #     MULTIPLIER:
  #     - 0.4
  #     - 1.0
  #     ELEMENT_WISE: true
  #     P: 1.0
  #     REPLACE: false
  # - BLUR:
  #     BLUR_LIMIT:
  #     - 3
  #     - 3 
  #     P: 1.0
  #     REPLACE: false
  # - ROTATE:
  #     LIMIT:
  #     - -45
  #     - 45 
  #     P: 1.0
   - COLOR_JITTER:
      P: 1.0
      REPLACE: false
  FOLDER:
  # - train
  - valid
  # - test
  NUMBER_AUGMENT: 3
  PREFIX: aug
DATASET:
  DATASET_PATH:
  - ./dataset
  # - /media/kan/kan_ex/digital_1_100_set1 
  # - /media/kan/kan_ex/digital_1_100_set2 
  # - /media/kan/kan_ex/
  # - datasets/digital/digital_1_100_set1
  # - /Users/kantip/Desktop/work/ABC_training/datasets/digital/digital_1_100_set2
  # - datasets/user13_101223
  DATASET_TYPE: digital
  FINAL_DATASET_PATH: dataset_new
  PERCENT_TEST: 5
  PERCENT_TRAIN: 90
  PERCENT_VAL: 5
PREPROCESS:
  FOLDER:
  # - train
  - valid
  # - test
  PREFIX: pre
  PREPROCESS_LIST:
  - CROP:
      ADD_PIXEL: 50
      CLASS_CROP: 1
      CLASS_IGNORE: 
      - 0
      NEED_RESIZE: true
      TARGET_HEIGHT: 640
      TARGET_WIDTH: 640
      REPLACE: false
  - RESIZE:
      TARGET_HEIGHT: 640
      TARGET_WIDTH: 640
      REPLACE: true
  # - GRAY:
  #     P: 1.0
  #     REPLACE: true