AUGMENT:
  AUGMENT_LIST: []
   # - RESIZE:
   #     TARGET_WIDTH: 640
   #     TARGET_HEIGHT: 640
   #     REPLACE: true
   # - CHANNEL_SHUFFLE:
   #    P: 0.5
   #    REPLACE: false
   # - MULTIPLICATIVE_NOISE:
   #    MULTIPLIER:
   #    - 0.4
   #    - 1.0
   #    ELEMENT_WISE: true
   #    P: 0.5
   #    REPLACE: false
   # - BLUR:
   #    BLUR_LIMIT:
   #    - 3
   #    - 3 
   #    P: 0.5
   #    REPLACE: false
   # - ROTATE:
   #    LIMIT:
   #    - -20
   #    - 20 
   #    P: 0.5
   # - COLOR_JITTER:
   #    BRIGHTNESS: 0.5
   #    CONTRAST: 0.5
   #    SATURATION: 0.5
   #    HUE: 0.5
   #    P: 0.75
   #    REPLACE: false
   # - LONGEST_MAX_SIZE:
   #    MAX_SIZE: 640
   #    P: 1.0
   #    REPLACE: false
   # - PAD_IF_NEEDED:
   #    MIN_WIDTH: 640
   #    MIN_HEIGHT: 640
   #    P: 1.0
   #    REPLACE: false
  FOLDER:
  - train
  - valid
#   - test
  NUMBER_AUGMENT: 3
  PREFIX: aug
DATASET:
  DATASET_PATH:
  - test_set1_200
  # - datasets/dial_for_number/user1/set1_1750
  # - datasets/dial_for_number/user2/set1_1500
  # - datasets/dial_for_number/user3/set1_1500 
  # - datasets/dial_for_number/user4/set1_1478
  # - datasets/dial_for_number/user5/set1_1000
  # - datasets/dial_for_number/user6/set1_1748
  # - datasets/dial_for_number/user7/set1_1494
  # - datasets/dial_for_number/user8/set1_1495
  # - datasets/dial_for_number/user10/set1_1499
  DATASET_TYPE: clock
  FINAL_DATASET_PATH: dataset_new/clock/test_set1_200/clock
  PERCENT_TEST: 0
  PERCENT_TRAIN: 100
  PERCENT_VAL: 0
PREPROCESS:
  FOLDER:
  - train
  - valid
  - test
  PREFIX: pre
  PREPROCESS_LIST:
  - CROP:
      ADD_PIXEL: 0
      CLASS_CROP_LIST: 
      - 0
      CLASS_IGNORE: []
      NEED_RESIZE: false
      TARGET_HEIGHT: 640
      TARGET_WIDTH: 640
      REPLACE: true
      REMOVE_ORIGINAL: true
  - RESIZE:
      TARGET_HEIGHT: 640
      TARGET_WIDTH: 640
      REPLACE: true
  - GRAY:
      P: 1.0
      REPLACE: true
  - GRAY_EROSION_DILATE:
      P: 1.0
      REPLACE: true
  - CLOCK:
      PREPROCESS_MIN_HEAD: false # remove min that overlap with head
      PREPROCESS_MIN_MAX: true # when have multiple min and max use the average min, max
      PREPROCESS_ONLY_ONE_GAUGE: true # choose image that has only one gauge in each image
      PREPROCESS_FULL_CLASS: true # choose image that has min, max , head, center
      REPLACE: true
  - RESIZE_BB:
      PERCENT: 50
      CLASS : [1,2] # add size of min and max
      REPLACE: true
  - RESIZE_BB:
      PERCENT: 75
      CLASS : [4] # add size of head
      REPLACE: true