
DATASET:
  DATASET_PATH:
  #TODO: for number dataset
  - dataset_process/number/number_process_color_own/number
  DATASET_TYPE: number
  FINAL_DATASET_PATH: dataset_process/number/number_process_gray_own/number
  PERCENT_TEST: 0
  PERCENT_TRAIN: 100
  PERCENT_VAL: 0
PREPROCESS:
  FOLDER:
  - train
  - valid
  - test
  PREFIX: pre
  PREPROCESS_LIST:
  - RESIZE:
      TARGET_HEIGHT: 640
      TARGET_WIDTH: 640
      REPLACE: true
  - GRAY:
      P: 1.0
      REPLACE: true
AUGMENT:
  AUGMENT_LIST: []  
  FOLDER:
  - train
  NUMBER_AUGMENT: 0 # augment 0
  PREFIX: aug