DATASET:
  DATASET_PATH:
  #TODO: for number dataset
  #FIXME: internet data
  - high_resolution/number/svhn/test
  - high_resolution/number/svhn/train
  DATASET_TYPE: number
  FINAL_DATASET_PATH: dataset_process/number/number_process_color_internet/number
  PERCENT_TEST: 0
  PERCENT_TRAIN: 100
  PERCENT_VAL: 0
PREPROCESS:
  FOLDER:
  - train
  - valid
  - test
  PREFIX: pre
  PREPROCESS_LIST:
  - RESIZE:
      TARGET_HEIGHT: 2048
      TARGET_WIDTH: 2048
      REPLACE: true
AUGMENT:
  AUGMENT_LIST:  
   - RESIZE:
       TARGET_WIDTH: 2048
       TARGET_HEIGHT: 2048
       REPLACE: true
   - CHANNEL_SHUFFLE:
      P: 0.25
      REPLACE: false
   - MULTIPLICATIVE_NOISE:
      MULTIPLIER:
      - 0.4
      - 1.0
      ELEMENT_WISE: true
      P: 0.25
      REPLACE: false
   - BLUR:
      BLUR_LIMIT:
      - 3
      - 3 
      P: 0.25
      REPLACE: false
   - ROTATE:
      LIMIT:
      - -20
      - 20 
      P: 0.25
   - COLOR_JITTER:
      BRIGHTNESS: 0.5
      CONTRAST: 0.5
      SATURATION: 0.5
      HUE: 0.5
      P: 0.5
      REPLACE: false
   - LONGEST_MAX_SIZE:
      MAX_SIZE: 2048
      P: 1.0
      REPLACE: false
   - PAD_IF_NEEDED:
      MIN_WIDTH: 2048
      MIN_HEIGHT: 2048
      P: 1.0
      REPLACE: false
  FOLDER:
  - train
  NUMBER_AUGMENT: 0 # No need to augment for internet dataset
  PREFIX: aug