DATASET:
  DATASET_PATH:
  #TODO: for digital dataset
  - dataset_process/digital/digital_process_gray_own/digital
  DATASET_TYPE: digital
  FINAL_DATASET_PATH: dataset_process_final/digital/digital_process_gray_final/digital
  PERCENT_TEST: 1
  PERCENT_TRAIN: 98
  PERCENT_VAL: 1
PREPROCESS:
  FOLDER:
  - train
  - valid
  - test
  PREFIX: pre
  PREPROCESS_LIST: 
  - RESIZE:
       TARGET_WIDTH: 640
       TARGET_HEIGHT: 640
       REPLACE: true
AUGMENT:
  AUGMENT_LIST: []  
  FOLDER: 
  - train
  NUMBER_AUGMENT: 0 # augment 3 image for own dataset
  PREFIX: aug