DATASET:
  DATASET_PATH:
  #TODO: for number dataset
  - dataset_process/digital/digital_process_color_own/digital
  DATASET_TYPE: digital
  FINAL_DATASET_PATH: dataset_process/digital/digital_process_gray_own/digital
  PERCENT_TEST: 0
  PERCENT_TRAIN: 100
  PERCENT_VAL: 0
PREPROCESS:
  FOLDER:
  - train
  - valid
  - test
  PREFIX: pre
  PREPROCESS_LIST:
  - RESIZE:
      TARGET_HEIGHT: 2048
      TARGET_WIDTH: 2048
      REPLACE: true
  - GRAY:
      P: 1.0
      REPLACE: true
AUGMENT:
  AUGMENT_LIST: []  
  FOLDER:
  - train
  NUMBER_AUGMENT: 0 # augment 0
  PREFIX: aug